name: DogBreeds
packages:
  Data:
    path: Data
  Domain: 
    path: Domain
  Injector: 
    path: Injector
targets:
  DogBreeds:
    type: application
    platform: iOS
    deploymentTarget: "15.2"
    sources: 
      - path: DogBreeds
    dependencies:
      - package: Injector
      - package: Domain
    scheme: 
      gatherCoverageData: true
      testTargets: 
        - name: DogBreedsTests
  DogBreedsTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.2"
    sources:
      - path: DogBreedsTests